<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LuBan.AIAgent" Version="2026.8.171" />
    <PackageReference Include="LuBan.Logging" Version="2026.8.171" />
    <PackageReference Include="LuBan.Orm" Version="2026.8.171" />
    <PackageReference Include="LuBan.DI" Version="2026.8.171" />
    <PackageReference Include="LuBan.Common" Version="2026.8.171" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.9.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.29.0" />
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="2.0.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.217" />
  </ItemGroup>
</Project>